name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
        if_key_exists: replace

    - name: Test SSH connection
      run: |
        ssh -o StrictHostKeyChecking=no root@46.202.163.122 'echo "SSH connection successful"'

    - name: Deploy to VPS
      run: |
        # Deploy frontend
        rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" dist/ root@46.202.163.122:/var/www/brainlogic/html/

        # Deploy backend (excluding node_modules and .env)
        rsync -avz --exclude='node_modules' --exclude='.env' -e "ssh -o StrictHostKeyChecking=no" backend/ root@46.202.163.122:/var/www/brainlogic/backend/

        # Restart backend service
        ssh -o StrictHostKeyChecking=no root@46.202.163.122 'cd /var/www/brainlogic/backend && npm install --production && pm2 restart brainlogic-api || pm2 start server.js --name brainlogic-api'

        # Reload Nginx
        ssh -o StrictHostKeyChecking=no root@46.202.163.122 'systemctl reload nginx'
